[project]
authors = ["Carl Caulkett <carl.caulkett@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max-nightly",
    "https://repo.prefix.dev/mojo-community",
]
description = "Testing a2svior's lightbug_http web server package"
name = "ca_web"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "magic run mojo test_packages.mojo"
default = "magic run mojo client.mojo"

[dependencies]
max = "*"
lightbug_http = ">=0.1.9"
